name: "WorldGuardEvents"
description: Provides other plugins with valuable events concerning WorldGuard regions.
version: ${project.version}
api-version: 1.13
main: net.raidstone.wgevents.WorldGuardEvents
author: Weby
depend: [WorldGuard]